# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, "8.0" # 第一行指定平台和版本
inhibit_all_warnings!

# /Users/zhouyong/Desktop/EasyUploader/iOS/Podfile
# puts __FILE__
# /Users/zhouyong/Desktop/EasyUploader/iOS
# puts File.dirname(__FILE__)

pod_file_path = File.dirname(__FILE__)
flutter_application_path = File.expand_path("../easyuploader_flutter")
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

pod 'AFNetworking', '~> 3.0'
#pod "Qiniu", :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
pod 'Qiniu', '~> 7.2.6'
pod 'HappyDNS', '~> 0.3'
pod 'CocoaLumberjack', '~> 3.2.1'
pod 'Masonry', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ReactiveCocoa', '~> 2.1.8'
pod 'JGPhotoBrowser', '~> 1.2.1'
# pod 'Realm', '~> 2.10.2'
pod 'Realm'

target 'EasyUploader' do
	puts 'target myproject install flutter pods start'
    install_all_flutter_pods(flutter_application_path)
    puts 'target myproject install flutter pods end'
end

target 'EasyUploaderTests' do

end

target 'EasyUploaderUITests' do

end

